# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [github_action_deploy]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          # Replace with your Workload Identity Provider Location
          workload_identity_provider: projects/374339991344/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          # Replace with your GitHub Service Account
          service_account: github-actions-service-account@fagfellesskap-test-b760.iam.gserviceaccount.com

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v1"
        with:
          # Name of the Cloud Function, same as the entry point name
          name: "helloWorld"
          # Runtime to use for the function
          runtime: "nodejs16"
          source_dir: "experimental"
          region: "europe-west1"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Example of using the output
      - id: "test"
        # run: 'curl "${{ steps.deploy.outputs.url }}"'
        run: "gcloud functions call helloWorld"